---

- name: Ensure OpenVPN packages are installed
  ansible.builtin.apt:
    name:
      - openvpn
      - easy-rsa
    state: present
    update_cache: yes
  become: yes

- name: Ensure that we can start openvpn
  ansible.builtin.systemd:
    name: openvpn
    enabled: true
  become: yes

- name: Copy openvpn defaults file
  ansible.builtin.copy:
    src: openvpn_defaults
    dest: /etc/default/openvpn
  become: yes

- name: Setup openvpn configuration
  ansible.builtin.template:
    src: server.conf.j2
    dest: /etc/openvpn/server.conf
  become: yes

- name: Copy easy rsa
  ansible.builtin.command: cp -R /usr/share/easy-rsa /etc/openvpn/easy-rsa
  args:
    creates: /etc/openvpn/easy-rsa
  changed_when: true

- name: Copy easy-rsa vars
  ansible.builtin.template:
    src: ca_vars.j2
    dest: /etc/openvpn/easy-rsa/ca_vars
  become: yes

- name: Copy easy-rsa server vars
  ansible.builtin.template:
    src: server_vars.j2
    dest: /etc/openvpn/easy-rsa/server_vars
  become: yes

- name: Create keys
  ansible.builtin.file:
    path: /etc/openvpn/easy-rsa/keys
    mode: '0600'
    state: directory
  become: yes

- name: Create CA
  ansible.builtin.shell: ". ./ca_vars && ./pkitool --initca && touch keys/index.txt && echo 01 > keys/serial"
  become: yes
  args:
    chdir: /etc/openvpn/easy-rsa
    creates: /etc/openvpn/easy-rsa/keys/ca.key
  changed_when: true

- name: Build DH
  ansible.builtin.shell: ". ./ca_vars && ./build-dh"
  become: yes
  args:
    chdir: /etc/openvpn/easy-rsa
    creates: /etc/openvpn/easy-rsa/keys/dh2048.pem
  changed_when: true

- name: Server Key
  ansible.builtin.shell: ". ./server_vars && ./pkitool --server {{ openvpn_server_key_name }}"
  become: yes
  args:
    chdir: /etc/openvpn/easy-rsa
    creates: /etc/openvpn/easy-rsa/keys/{{ openvpn_server_key_name }}.key
  changed_when: true

- name: Client keys
  ansible.builtin.shell: ". ./server_vars && export KEY_OU='{{ item }}' && export KEY_NAME='{{ item }}' && ./pkitool {{ item }}"
  loop: "{{ openvpn_clients }}"
  args:
    chdir: /etc/openvpn/easy-rsa
    creates: "/etc/openvpn/easy-rsa/keys/{{ item }}.key"
  changed_when: true

- name: Client configs
  ansible.builtin.template:
    src: client.ovpn.j2
    dest: /etc/openvpn/easy-rsa/keys/{{ item }}.conf
  loop: "{{ openvpn_clients }}"

- name: Create ccd dir
  ansible.builtin.file:
    path: /etc/openvpn/ccd
    state: directory
  become: yes

- name: Restart the server
  ansible.builtin.service:
    name: openvpn
    state: restarted
  become: yes
