---
- name: install numix theme and install circle icon theme
  apt:
    name:
      - numix-icon-theme-circle
      - numix-gtk-theme
      - gnome-tweaks
      - nautilus-image-converter
    state: present
  become: yes

- name: Create dconf cache dir
  become: yes
  become_user: "{{ ansible_user_id }}"
  file:
    path: "~/.cache/dconf"
    state: directory
    owner: "{{ ansible_user_id }}"
    mode: '0775'

- name: Install dependencies for gsettings
  apt:
   name: dbus-x11
   state: present
  become: yes

- name: Set icons to numix circle+
  become: yes
  become_user: "{{ ansible_user_id }}"
  gsettings:
    key: org.gnome.desktop.interface.icon-theme
    value: Numix-Circle

# - name: Set number of worspaces to 4
#   become: yes
#   become_user: "{{ ansible_user_id }}"
#   gsettings:
#     key: org.gnome.desktop.wm.preferences.num-workspaces
#     value: 4

# - name: Disable dynamic workspaces
#   become: yes
#   become_user: "{{ ansible_user_id }}"
#   gsettings:
#     key: org.gnome.shell.overrides.dynamic-workspaces
#     value: 'false'

# - name: Enable workspaces on all screens
#   become: yes
#   become_user: "{{ ansible_user_id }}"
#   gsettings:
#     key: org.gnome.shell.overrides.workspaces-only-on-primary
#     value: 'false'

- name: Show date
  become: yes
  become_user: "{{ ansible_user_id }}"
  gsettings:
    key: org.gnome.desktop.interface.clock-show-date
    value: 'true'

- name: Show seconds
  become: yes
  become_user: "{{ ansible_user_id }}"
  gsettings:
    key: org.gnome.desktop.interface.clock-show-seconds
    value: 'true'

- name: Add minimize to button layout
  become: yes
  become_user: "{{ ansible_user_id }}"
  gsettings:
    key: org.gnome.desktop.wm.preferences.button-layout
    value: ":minimize,close"

- name: Copy Wallpaper
  copy:
    src: Grass.jpg
    dest: "/usr/share/backgrounds/"
    mode: '0644'
  become: yes

# - name: Set Wallpaper
#   become: yes
#   become_user: "{{ ansible_user_id }}"
#   gsettings:
#     key:  org.gnome.desktop.background.picture-uri
#     value: "file:///usr/share/backgrounds/Grass.jpg"

# - name: Remember numlock state
#   become: yes
#   become_user: "{{ ansible_user_id }}"
#   gsettings:
#     key: org.gnome.settings-daemon.peripherals.keyboard.remember-numlock-state
#     value: 'true'


