---
- name: Check if MySQL is already installed.
  ansible.builtin.stat:
    path: /etc/init.d/mysql
  register: mysql_installed

- name: Update apt cache if MySQL is not yet installed.
  ansible.builtin.apt:
    update_cache: yes
  when: not mysql_installed.stat.exists

- name: Ensure MySQL packages are installed.
  ansible.builtin.apt:
    name:
      - python3-mysqldb
      - mariadb-client
      - mariadb-server
    state: present
