---
- name: Add contrib and non-free section to debian repositories
  apt_repository:
    repo: 'deb http://httpredir.debian.org/debian {{ ansible_distribution_release }} contrib non-free'
    state: present
  become: yes
  when: ansible_distribution == 'Debian'

- name: Install debconf, debconf utils and git required for ansible deployment
  apt:
    name:
      - sudo
      - curl
      - unzip
      - debconf
      - debconf-utils
      - software-properties-common
      - git
      - apt-transport-https
      - dnsutils
    state: present
    update_cache: yes
  become: yes

- name: Add root bashrc
  copy:
    src: bashrc
    dest: /root/.bashrc
    mode: '0644'
  become: yes
  when: ansible_distribution == 'Debian'