---
- name: Download GitLab GPG key
  ansible.builtin.get_url:
    url: https://packages.gitlab.com/runner/gitlab-runner/gpgkey
    dest: /tmp/runner_gitlab-runner.gpg
    mode: '0644'
  become: yes

- name: Dearmor GitLab GPG key
  ansible.builtin.command:
    cmd: gpg --dearmor -o /usr/share/keyrings/runner_gitlab-runner-archive-keyring.gpg /tmp/runner_gitlab-runner.gpg
    creates: /usr/share/keyrings/runner_gitlab-runner-archive-keyring.gpg
  become: yes
  changed_when: true

- name: Add GitLab repository with signed-by option
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/runner_gitlab-runner-archive-keyring.gpg] https://packages.gitlab.com/runner/gitlab-runner/debian/ {{ ansible_distribution_release }} main"
    state: present
    filename: gitlab
  become: yes

- name: Add APT pinning for gitlab-runner repository
  ansible.builtin.copy:
    dest: /etc/apt/preferences.d/gitlab
    content: |
      Package: gitlab-runner
      Pin: origin packages.gitlab.com
      Pin-Priority: 1001
  become: yes

- name: Install gitlab-runner
  ansible.builtin.apt:
    name: gitlab-runner
    state: present
  become: yes
