---

- name: Create adaxisoft.be group
  ansible.builtin.group:
    name: "{{ adaxisoft_be_group }}"

- name: Check adaxisoft.be was already installed
  ansible.builtin.stat:
    path: "{{ adaxisoft_be_home }}"
  register: adaxisoft_be_root

- name: Deploy adaxisoft.be
  ansible.builtin.git:
    repo: https://github.com/adaxi/adaxisoft.be.git
    dest: "{{ adaxisoft_be_home }}"
  when: not adaxisoft_be_root.stat.exists

- name: Create adaxisoft.be user
  ansible.builtin.user:
    name: "{{ adaxisoft_be_user }}"
    shell: /bin/nologin
    group: "{{ adaxisoft_be_group }}"
    home: "{{ adaxisoft_be_home }}"

- name: Chown to adaxisoft_be
  ansible.builtin.file:
    path: "{{ adaxisoft_be_home }}"
    owner: "{{ adaxisoft_be_group }}"
    group: "{{ adaxisoft_be_user }}"
    recurse: true

- name: Install NGINX configuration
  ansible.builtin.include_tasks: nginx.yml

- name: Install adaxisoft-api configuration
  ansible.builtin.include_tasks: adaxisoft-api.yml

- name: Install adaxisoft-blog configuration
  ansible.builtin.include_tasks: adaxisoft-blog.yml

- name: Reload NGINX
  ansible.builtin.service:
    name: nginx
    state: reloaded
