---
- name: Make adaxisoft_be.conf nginx configuration is available
  ansible.builtin.template:
    dest: /etc/nginx/sites-available/adaxisoft_be.conf
    src: nginx.adaxisoft_be.conf.j2
  notify: Reload nginx

- name: Enable nginx adaxisoft_be.conf
  ansible.builtin.file:
    src: /etc/nginx/sites-available/adaxisoft_be.conf
    dest: /etc/nginx/sites-enabled/adaxisoft_be.conf
    state: link
