---

- name: Install acl
  ansible.builtin.apt:
    name: acl
    state: present

- name: Install nginx configuration
  ansible.builtin.include_tasks: nginx.yml

- name: Install mariadb configuration
  ansible.builtin.include_tasks: mariadb.yml

- name: Install lusoleaves.com configuration
  ansible.builtin.include_tasks: container.yml

# - name: Reload nginx
#   service: name=nginx state=reloaded
