---

- name: Make lusoleaves_com.conf available
  ansible.builtin.template:
    src: nginx.lusoleaves_com.conf.j2
    dest: /etc/nginx/sites-available/lusoleaves_com.conf
  notify: Reload nginx

- name: Enable lusoleaves_com.conf
  ansible.builtin.file:
    src: /etc/nginx/sites-available/lusoleaves_com.conf
    dest: /etc/nginx/sites-enabled/lusoleaves_com.conf
    state: link
