---

- name: Create bonaert.eu group
  ansible.builtin.group:
    name: "{{ bonaert_eu_group }}"

- name: Create empty dir
  ansible.builtin.file:
    path: /dev/empty
    state: directory

- name: Check if bonaert.eu was already installed
  ansible.builtin.stat:
    path: "{{ bonaert_eu_home }}"
  register: bonaert_eu_root

- name: Deploy bonaert.eu
  ansible.builtin.git:
    repo: https://github.com/adaxi/adaxisoft.be.git
    dest: "{{ bonaert_eu_home }}"
  when: not bonaert_eu_root.stat.exists

- name: Create bonaert.eu user
  ansible.builtin.user:
    name: "{{ bonaert_eu_user }}"
    shell: /bin/nologin
    group: "{{ bonaert_eu_group }}"
    home: "{{ bonaert_eu_home }}"
    skeleton: /dev/empty

- name: Chown to bonaert_eu
  ansible.builtin.file:
    path: "{{ bonaert_eu_home }}"
    owner: "{{ bonaert_eu_group }}"
    group: "{{ bonaert_eu_user }}"
    recurse: true

- name: Install nginx configuration
  ansible.builtin.include_tasks: nginx.yml

- name: Reload nginx
  ansible.builtin.service:
    name: nginx
    state: reloaded
