---

- name: Get stat of webstorm
  ansible.builtin.stat:
    path: "{{ webstorm_bin }}"
  register: webstorm_stat

- name: Test if webstorm is executable
  ansible.builtin.fail:
    msg: "{{ webstorm_bin }} isn't executable"
  when: not webstorm_stat.stat.xgrp
