- name: Add docker public key
  apt_key:
    url: "https://download.docker.com/linux/debian/gpg"
    state: present

- name: Add docker repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
    state: present

- name: Ensure docker is installed
  apt: 
    name: 
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
      - docker-buildx-plugin
      - python3-docker
    update_cache: true
    state: present

- name: Ensure docker deamon is running
  service:
    name: docker
    state: started
    enabled: true