---
- name: Make vaultwarden.adaxisoft_be.conf nginx configuration is available
  ansible.builtin.template:
    dest: /etc/nginx/sites-available/vaultwarden.adaxisoft_be.conf
    src: nginx.vaultwarden.adaxisoft_be.conf.j2
  notify: Reload nginx

- name: Enable nginx vaultwarden.adaxisoft_be.conf
  ansible.builtin.file:
    src: /etc/nginx/sites-available/vaultwarden.adaxisoft_be.conf
    dest: /etc/nginx/sites-enabled/vaultwarden.adaxisoft_be.conf
    state: link
